2016-08-01 20:34:40,974:INFO:ncpa_windows:Parsed config from: ['C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg', 'C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg.d\\example.cfg']
2016-08-01 20:34:40,974:INFO:ncpa_windows:Looking for plugins at: C:\Users\Jake\Documents\ncpa\agent\plugins
2016-08-01 20:34:40,974:ERROR:ncpa_windows:get() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "C:\Users\Jake\Documents\ncpa\agent\ncpa_windows.py", line 136, in start
    ssl_str_version = self.config.get('listener', 'ssl_version', 'TLSv1')
TypeError: get() takes 3 positional arguments but 4 were given
2016-08-01 20:34:48,257:INFO:ncpa_windows:Parsed config from: ['C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg', 'C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg.d\\example.cfg']
2016-08-01 20:34:48,257:INFO:ncpa_windows:Looking for plugins at: C:\Users\Jake\Documents\ncpa\agent\plugins
2016-08-01 20:34:48,257:ERROR:ncpa_windows:get() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "C:\Users\Jake\Documents\ncpa\agent\ncpa_windows.py", line 136, in start
    ssl_str_version = self.config.get('listener', 'ssl_version', 'TLSv1')
TypeError: get() takes 3 positional arguments but 4 were given
2016-08-01 20:35:58,633:INFO:ncpa_windows:Parsed config from: ['C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg', 'C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg.d\\example.cfg']
2016-08-01 20:35:58,633:INFO:ncpa_windows:Looking for plugins at: C:\Users\Jake\Documents\ncpa\agent\plugins
2016-08-01 20:35:58,633:INFO:ncpa_windows:Using SSL version TLSv1_2
2016-08-01 20:36:21,191:ERROR:app:Exception on /gui/ [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 176, in gui_index
    info = make_info_dict()
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 47, in make_info_dict
    uptime = unicode(now - __STARTED__)
NameError: name 'unicode' is not defined
2016-08-01 20:36:24,000:ERROR:app:Exception on /gui/ [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 176, in gui_index
    info = make_info_dict()
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 47, in make_info_dict
    uptime = unicode(now - __STARTED__)
NameError: name 'unicode' is not defined
2016-08-01 20:36:44,169:ERROR:app:Exception on /gui/api [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 467, in view_api
    info = make_info_dict()
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 47, in make_info_dict
    uptime = unicode(now - __STARTED__)
NameError: name 'unicode' is not defined
2016-08-01 20:37:04,836:INFO:ncpa_windows:Parsed config from: ['C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg', 'C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg.d\\example.cfg']
2016-08-01 20:37:04,836:INFO:ncpa_windows:Looking for plugins at: C:\Users\Jake\Documents\ncpa\agent\plugins
2016-08-01 20:37:04,836:INFO:ncpa_windows:Using SSL version TLSv1_2
2016-08-01 20:37:10,631:ERROR:app:Exception on /gui/api [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 467, in view_api
    info = make_info_dict()
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 48, in make_info_dict
    uptime = uptime.split('.', 1)[0]
AttributeError: 'datetime.timedelta' object has no attribute 'split'
2016-08-01 20:37:54,821:INFO:ncpa_windows:Parsed config from: ['C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg', 'C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg.d\\example.cfg']
2016-08-01 20:37:54,822:INFO:ncpa_windows:Looking for plugins at: C:\Users\Jake\Documents\ncpa\agent\plugins
2016-08-01 20:37:54,822:INFO:ncpa_windows:Using SSL version TLSv1_2
2016-08-01 20:38:02,033:ERROR:app:Exception on /api/ [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 537, in api
    node = psapi.getter(accessor, config, full_path)
NameError: name 'psapi' is not defined
2016-08-01 20:38:11,057:ERROR:app:Exception on /api/ [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 537, in api
    node = psapi.getter(accessor, config, full_path)
NameError: name 'psapi' is not defined
2016-08-01 20:38:33,395:INFO:ncpa_windows:Parsed config from: ['C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg', 'C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg.d\\example.cfg']
2016-08-01 20:38:33,395:INFO:ncpa_windows:Looking for plugins at: C:\Users\Jake\Documents\ncpa\agent\plugins
2016-08-01 20:38:33,395:INFO:ncpa_windows:Using SSL version TLSv1_2
2016-08-01 20:38:44,232:ERROR:app:Exception on /api/ [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 57, in walk
    for name, child in self.children.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
2016-08-01 20:39:17,179:INFO:ncpa_windows:Parsed config from: ['C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg', 'C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg.d\\example.cfg']
2016-08-01 20:39:17,179:INFO:ncpa_windows:Looking for plugins at: C:\Users\Jake\Documents\ncpa\agent\plugins
2016-08-01 20:39:17,180:INFO:ncpa_windows:Using SSL version TLSv1_2
2016-08-01 20:39:24,215:ERROR:nodes:name 'server' is not defined
Traceback (most recent call last):
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 124, in walk
    values, unit = self.method(*args, **kwargs)
TypeError: <lambda>() got an unexpected keyword argument 'accessor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 61, in walk
    stat.update(child.walk(*args, **kwargs))
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 126, in walk
    values, unit = self.method()
  File "C:\Users\Jake\Documents\ncpa\agent\listener\psapi.py", line 88, in <lambda>
    sys_agent = RunnableNode('agent_version', method=lambda: (server.__VERSION__, ''))
NameError: name 'server' is not defined
2016-08-01 20:39:24,220:ERROR:app:Exception on /api/ [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 557, in api
    indent=None if request.is_xhr else 4),
  File "C:\Python35\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\Python35\lib\json\encoder.py", line 200, in encode
    chunks = list(chunks)
  File "C:\Python35\lib\json\encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Python35\lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Python35\lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Python35\lib\json\encoder.py", line 436, in _iterencode
    o = _default(o)
  File "C:\Python35\lib\json\encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: dict_keys(['test.ps1', 'test23.ps1']) is not JSON serializable
2016-08-01 20:40:29,758:INFO:ncpa_windows:Parsed config from: ['C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg', 'C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg.d\\example.cfg']
2016-08-01 20:40:29,759:INFO:ncpa_windows:Looking for plugins at: C:\Users\Jake\Documents\ncpa\agent\plugins
2016-08-01 20:40:29,759:INFO:ncpa_windows:Using SSL version TLSv1_2
2016-08-01 20:40:36,604:ERROR:app:Exception on /api/ [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 557, in api
    indent=None if request.is_xhr else 4),
  File "C:\Python35\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\Python35\lib\json\encoder.py", line 200, in encode
    chunks = list(chunks)
  File "C:\Python35\lib\json\encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Python35\lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Python35\lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Python35\lib\json\encoder.py", line 436, in _iterencode
    o = _default(o)
  File "C:\Python35\lib\json\encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: dict_keys(['test23.ps1', 'test.ps1']) is not JSON serializable
2016-08-01 20:41:29,838:INFO:ncpa_windows:Parsed config from: ['C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg', 'C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg.d\\example.cfg']
2016-08-01 20:41:29,838:INFO:ncpa_windows:Looking for plugins at: C:\Users\Jake\Documents\ncpa\agent\plugins
2016-08-01 20:41:29,838:INFO:ncpa_windows:Using SSL version TLSv1_2
2016-08-01 20:41:46,524:ERROR:app:Exception on /api/ [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 557, in api
    indent=None if request.is_xhr else 4),
  File "C:\Python35\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\Python35\lib\json\encoder.py", line 200, in encode
    chunks = list(chunks)
  File "C:\Python35\lib\json\encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Python35\lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Python35\lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Python35\lib\json\encoder.py", line 436, in _iterencode
    o = _default(o)
  File "C:\Python35\lib\json\encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: dict_keys(['test.ps1', 'test23.ps1']) is not JSON serializable
2016-08-01 20:41:58,230:INFO:ncpa_windows:Parsed config from: ['C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg', 'C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg.d\\example.cfg']
2016-08-01 20:41:58,230:INFO:ncpa_windows:Looking for plugins at: C:\Users\Jake\Documents\ncpa\agent\plugins
2016-08-01 20:41:58,230:INFO:ncpa_windows:Using SSL version TLSv1_2
2016-08-01 20:42:05,096:ERROR:app:Exception on /api/ [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 557, in api
    indent=None if request.is_xhr else 4),
  File "C:\Python35\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\Python35\lib\json\encoder.py", line 200, in encode
    chunks = list(chunks)
  File "C:\Python35\lib\json\encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Python35\lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Python35\lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Python35\lib\json\encoder.py", line 436, in _iterencode
    o = _default(o)
  File "C:\Python35\lib\json\encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: dict_keys(['test23.ps1', 'test.ps1']) is not JSON serializable
2016-08-01 20:44:00,202:ERROR:app:Exception on /api/ [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 557, in api
    indent=None if request.is_xhr else 4),
  File "C:\Python35\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\Python35\lib\json\encoder.py", line 200, in encode
    chunks = list(chunks)
  File "C:\Python35\lib\json\encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Python35\lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Python35\lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Python35\lib\json\encoder.py", line 436, in _iterencode
    o = _default(o)
  File "C:\Python35\lib\json\encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: dict_keys(['test23.ps1', 'test.ps1']) is not JSON serializable
2016-08-01 20:44:03,150:INFO:ncpa_windows:Parsed config from: ['C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg', 'C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg.d\\example.cfg']
2016-08-01 20:44:03,150:INFO:ncpa_windows:Looking for plugins at: C:\Users\Jake\Documents\ncpa\agent\plugins
2016-08-01 20:44:03,150:INFO:ncpa_windows:Using SSL version TLSv1_2
2016-08-01 20:44:08,488:ERROR:app:Exception on /api/ [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 557, in api
    indent=None if request.is_xhr else 4),
  File "C:\Python35\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\Python35\lib\json\encoder.py", line 200, in encode
    chunks = list(chunks)
  File "C:\Python35\lib\json\encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Python35\lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Python35\lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Python35\lib\json\encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "C:\Python35\lib\json\encoder.py", line 436, in _iterencode
    o = _default(o)
  File "C:\Python35\lib\json\encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <listener.pluginnodes.PluginNode object at 0x03887E90> is not JSON serializable
2016-08-01 20:44:35,930:INFO:ncpa_windows:Parsed config from: ['C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg', 'C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg.d\\example.cfg']
2016-08-01 20:44:35,930:INFO:ncpa_windows:Looking for plugins at: C:\Users\Jake\Documents\ncpa\agent\plugins
2016-08-01 20:44:35,930:INFO:ncpa_windows:Using SSL version TLSv1_2
2016-08-01 20:52:22,811:INFO:ncpa_windows:Parsed config from: ['C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg', 'C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg.d\\example.cfg']
2016-08-01 20:52:22,811:INFO:ncpa_windows:Looking for plugins at: C:\Users\Jake\Documents\ncpa\agent\plugins
2016-08-01 20:52:22,811:INFO:ncpa_windows:Using SSL version TLSv1_2
2016-08-01 20:52:29,754:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:29] "GET / HTTP/1.1" 302 505 0.001016
2016-08-01 20:52:29,768:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:29] "GET /login HTTP/1.1" 200 2933 0.011999
2016-08-01 20:52:30,063:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:30] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 121552 0.205257
2016-08-01 20:52:30,065:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:30] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 24029 0.001017
2016-08-01 20:52:30,067:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:30] "GET /static/css/ncpa.css HTTP/1.1" 200 5435 0.002010
2016-08-01 20:52:30,069:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:30] "GET /static/js/jquery.2.2.4.min.js HTTP/1.1" 200 85863 0.001978
2016-08-01 20:52:30,071:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:30] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 37160 0.002002
2016-08-01 20:52:30,073:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:30] "GET /static/js/d3.v4.min.js HTTP/1.1" 200 211413 0.002002
2016-08-01 20:52:30,170:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:30] "GET /static/img/footer_lodyas.png HTTP/1.1" 200 33973 0.000986
2016-08-01 20:52:31,572:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:31] "POST /login HTTP/1.1" 302 545 0.001980
2016-08-01 20:52:31,575:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:31] "GET / HTTP/1.1" 302 513 0.001502
2016-08-01 20:52:31,583:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:31] "GET /gui/ HTTP/1.1" 200 5651 0.005527
2016-08-01 20:52:31,649:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:31] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 121552 0.002002
2016-08-01 20:52:31,651:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:31] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 24029 0.001001
2016-08-01 20:52:31,653:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:31] "GET /static/css/ncpa.css HTTP/1.1" 200 5435 0.001018
2016-08-01 20:52:31,655:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:31] "GET /static/js/jquery.2.2.4.min.js HTTP/1.1" 200 85863 0.001985
2016-08-01 20:52:31,657:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:31] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 37160 0.002017
2016-08-01 20:52:31,660:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:31] "GET /static/js/d3.v4.min.js HTTP/1.1" 200 211413 0.002986
2016-08-01 20:52:31,779:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:31] "GET /static/fonts/fontawesome-webfont.woff2?v=4.3.0 HTTP/1.1" 200 57067 0.001501
2016-08-01 20:52:33,628:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:33] "GET /gui/stats HTTP/1.1" 200 6173 0.005004
2016-08-01 20:52:33,663:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:33] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 121552 0.002001
2016-08-01 20:52:33,665:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:33] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 24029 0.001000
2016-08-01 20:52:33,667:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:33] "GET /static/css/ncpa.css HTTP/1.1" 200 5435 0.001000
2016-08-01 20:52:33,669:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:33] "GET /static/css/ncpa-graph.css HTTP/1.1" 200 794 0.001000
2016-08-01 20:52:33,672:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:33] "GET /static/js/jquery.2.2.4.min.js HTTP/1.1" 200 85863 0.001502
2016-08-01 20:52:33,674:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:33] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 37160 0.001502
2016-08-01 20:52:33,677:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:33] "GET /static/js/d3.v4.min.js HTTP/1.1" 200 211413 0.002502
2016-08-01 20:52:33,743:ERROR:app:Exception on /graph/cpu/percent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 400, in graph
    info['query_string'] = urllib.quote(query_string)
AttributeError: module 'urllib' has no attribute 'quote'
2016-08-01 20:52:33,766:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:33] "GET /graph/cpu/percent HTTP/1.1" 500 3356 0.027025
2016-08-01 20:52:33,770:ERROR:app:Exception on /graph/memory/virtual/percent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 400, in graph
    info['query_string'] = urllib.quote(query_string)
AttributeError: module 'urllib' has no attribute 'quote'
2016-08-01 20:52:33,810:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:33] "GET /graph/memory/virtual/percent HTTP/1.1" 500 3356 0.042977
2016-08-01 20:52:33,814:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:33] "GET /api/disk/logical HTTP/1.1" 200 453 0.003003
2016-08-01 20:52:33,865:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:33] "GET /api/interface/ HTTP/1.1" 200 1501 0.050288
2016-08-01 20:52:33,874:ERROR:app:Exception on /graph/disk/logical/C:|/used_percent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 400, in graph
    info['query_string'] = urllib.quote(query_string)
AttributeError: module 'urllib' has no attribute 'quote'
2016-08-01 20:52:33,901:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:33] "GET /graph/disk/logical/C:%7C/used_percent HTTP/1.1" 500 3356 0.030246
2016-08-01 20:52:33,901:ERROR:app:Exception on /graph/interface/VMware Network Adapter VMnet1/bytes_sent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 400, in graph
    info['query_string'] = urllib.quote(query_string)
AttributeError: module 'urllib' has no attribute 'quote'
2016-08-01 20:52:33,933:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:33] "GET /graph/interface/VMware%20Network%20Adapter%20VMnet1/bytes_sent?delta=1&units=K HTTP/1.1" 500 3356 0.031686
2016-08-01 20:52:33,936:ERROR:app:Exception on /graph/interface/VMware Network Adapter VMnet1/bytes_recv [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 400, in graph
    info['query_string'] = urllib.quote(query_string)
AttributeError: module 'urllib' has no attribute 'quote'
2016-08-01 20:52:33,961:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:33] "GET /graph/interface/VMware%20Network%20Adapter%20VMnet1/bytes_recv?delta=1&units=K HTTP/1.1" 500 3356 0.028155
2016-08-01 20:52:33,981:ERROR:app:Exception on /graph/interface/Ethernet/bytes_sent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 400, in graph
    info['query_string'] = urllib.quote(query_string)
AttributeError: module 'urllib' has no attribute 'quote'
2016-08-01 20:52:34,007:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:34] "GET /graph/interface/Ethernet/bytes_sent?delta=1&units=K HTTP/1.1" 500 3356 0.028822
2016-08-01 20:52:34,029:ERROR:app:Exception on /graph/interface/Ethernet/bytes_recv [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 400, in graph
    info['query_string'] = urllib.quote(query_string)
AttributeError: module 'urllib' has no attribute 'quote'
2016-08-01 20:52:34,059:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:34] "GET /graph/interface/Ethernet/bytes_recv?delta=1&units=K HTTP/1.1" 500 3356 0.030437
2016-08-01 20:52:34,064:ERROR:app:Exception on /graph/interface/VMware Network Adapter VMnet8/bytes_sent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 400, in graph
    info['query_string'] = urllib.quote(query_string)
AttributeError: module 'urllib' has no attribute 'quote'
2016-08-01 20:52:34,092:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:34] "GET /graph/interface/VMware%20Network%20Adapter%20VMnet8/bytes_sent?delta=1&units=K HTTP/1.1" 500 3356 0.033062
2016-08-01 20:52:34,092:ERROR:app:Exception on /graph/interface/Ethernet 3/bytes_sent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 400, in graph
    info['query_string'] = urllib.quote(query_string)
AttributeError: module 'urllib' has no attribute 'quote'
2016-08-01 20:52:34,112:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:34] "GET /graph/interface/Ethernet%203/bytes_sent?delta=1&units=K HTTP/1.1" 500 3356 0.020005
2016-08-01 20:52:34,117:ERROR:app:Exception on /graph/interface/Ethernet 3/bytes_recv [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 400, in graph
    info['query_string'] = urllib.quote(query_string)
AttributeError: module 'urllib' has no attribute 'quote'
2016-08-01 20:52:34,135:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:34] "GET /graph/interface/Ethernet%203/bytes_recv?delta=1&units=K HTTP/1.1" 500 3356 0.023081
2016-08-01 20:52:34,139:ERROR:app:Exception on /graph/interface/Loopback Pseudo-Interface 1/bytes_sent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 400, in graph
    info['query_string'] = urllib.quote(query_string)
AttributeError: module 'urllib' has no attribute 'quote'
2016-08-01 20:52:34,157:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:34] "GET /graph/interface/Loopback%20Pseudo-Interface%201/bytes_sent?delta=1&units=K HTTP/1.1" 500 3356 0.021022
2016-08-01 20:52:34,160:ERROR:app:Exception on /graph/interface/Loopback Pseudo-Interface 1/bytes_recv [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 400, in graph
    info['query_string'] = urllib.quote(query_string)
AttributeError: module 'urllib' has no attribute 'quote'
2016-08-01 20:52:34,180:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:34] "GET /graph/interface/Loopback%20Pseudo-Interface%201/bytes_recv?delta=1&units=K HTTP/1.1" 500 3356 0.023024
2016-08-01 20:52:34,184:ERROR:app:Exception on /graph/interface/VMware Network Adapter VMnet8/bytes_recv [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 400, in graph
    info['query_string'] = urllib.quote(query_string)
AttributeError: module 'urllib' has no attribute 'quote'
2016-08-01 20:52:34,202:INFO:handler:127.0.0.1 - - [2016-08-01 20:52:34] "GET /graph/interface/VMware%20Network%20Adapter%20VMnet8/bytes_recv?delta=1&units=K HTTP/1.1" 500 3356 0.021039
2016-08-01 20:53:20,973:INFO:ncpa_windows:Parsed config from: ['C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg', 'C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg.d\\example.cfg']
2016-08-01 20:53:20,973:INFO:ncpa_windows:Looking for plugins at: C:\Users\Jake\Documents\ncpa\agent\plugins
2016-08-01 20:53:20,973:INFO:ncpa_windows:Using SSL version TLSv1_2
2016-08-01 20:53:23,814:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:23] "GET /gui/stats HTTP/1.1" 302 517 0.001001
2016-08-01 20:53:23,828:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:23] "GET /login HTTP/1.1" 200 2954 0.012010
2016-08-01 20:53:24,109:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 121552 0.202197
2016-08-01 20:53:24,111:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 24029 0.001001
2016-08-01 20:53:24,120:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /static/css/ncpa.css HTTP/1.1" 200 5435 0.002002
2016-08-01 20:53:24,123:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /static/js/jquery.2.2.4.min.js HTTP/1.1" 200 85863 0.002002
2016-08-01 20:53:24,125:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /static/js/d3.v4.min.js HTTP/1.1" 200 211413 0.002002
2016-08-01 20:53:24,127:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 37160 0.001001
2016-08-01 20:53:24,178:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /static/img/footer_lodyas.png HTTP/1.1" 304 187 0.002004
2016-08-01 20:53:24,195:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /static/img/ncpa.png HTTP/1.1" 200 18888 0.002002
2016-08-01 20:53:24,200:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /static/img/ncpa.png HTTP/1.1" 200 18888 0.002000
2016-08-01 20:53:24,574:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "POST /login HTTP/1.1" 302 572 0.001001
2016-08-01 20:53:24,582:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /gui/stats HTTP/1.1" 200 6173 0.005043
2016-08-01 20:53:24,651:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /static/css/ncpa-graph.css HTTP/1.1" 200 794 0.001020
2016-08-01 20:53:24,731:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /graph/cpu/percent HTTP/1.1" 200 5556 0.010030
2016-08-01 20:53:24,734:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /graph/memory/virtual/percent HTTP/1.1" 200 5611 0.002983
2016-08-01 20:53:24,738:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /api/disk/logical HTTP/1.1" 200 453 0.003020
2016-08-01 20:53:24,793:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /api/interface/ HTTP/1.1" 200 1501 0.054054
2016-08-01 20:53:24,795:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /static/fonts/fontawesome-webfont.woff2?v=4.3.0 HTTP/1.1" 304 188 0.001003
2016-08-01 20:53:24,797:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /static/js/smoothie.js?_=1470102804702 HTTP/1.1" 200 33107 0.001015
2016-08-01 20:53:24,812:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /static/js/smoothie.js?_=1470102804703 HTTP/1.1" 200 33107 0.001001
2016-08-01 20:53:24,821:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /api/memory/virtual/percent HTTP/1.1" 200 269 0.003004
2016-08-01 20:53:24,827:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /graph/disk/logical/C:%7C/used_percent HTTP/1.1" 200 5646 0.004006
2016-08-01 20:53:24,832:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /graph/interface/VMware%20Network%20Adapter%20VMnet8/bytes_sent?delta=1&units=K HTTP/1.1" 200 5759 0.004004
2016-08-01 20:53:24,836:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /graph/interface/VMware%20Network%20Adapter%20VMnet8/bytes_recv?delta=1&units=K HTTP/1.1" 200 5772 0.003004
2016-08-01 20:53:24,840:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /graph/interface/Ethernet/bytes_sent?delta=1&units=K HTTP/1.1" 200 5680 0.003002
2016-08-01 20:53:24,844:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /graph/interface/Ethernet/bytes_recv?delta=1&units=K HTTP/1.1" 200 5680 0.003004
2016-08-01 20:53:24,848:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /graph/interface/Ethernet%203/bytes_sent?delta=1&units=K HTTP/1.1" 200 5677 0.003020
2016-08-01 20:53:24,853:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /graph/interface/Ethernet%203/bytes_recv?delta=1&units=K HTTP/1.1" 200 5677 0.004005
2016-08-01 20:53:24,857:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /graph/interface/Loopback%20Pseudo-Interface%201/bytes_sent?delta=1&units=K HTTP/1.1" 200 5762 0.004003
2016-08-01 20:53:24,863:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /graph/interface/Loopback%20Pseudo-Interface%201/bytes_recv?delta=1&units=K HTTP/1.1" 200 5762 0.005007
2016-08-01 20:53:24,866:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /static/js/smoothie.js?_=1470102804704 HTTP/1.1" 200 33107 0.002002
2016-08-01 20:53:24,869:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /graph/interface/VMware%20Network%20Adapter%20VMnet1/bytes_sent?delta=1&units=K HTTP/1.1" 200 5759 0.003020
2016-08-01 20:53:24,874:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /graph/interface/VMware%20Network%20Adapter%20VMnet1/bytes_recv?delta=1&units=K HTTP/1.1" 200 5759 0.004025
2016-08-01 20:53:24,876:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /static/js/smoothie.js?_=1470102804705 HTTP/1.1" 200 33107 0.001982
2016-08-01 20:53:24,880:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /api/disk/logical/C:%7C/used_percent HTTP/1.1" 200 274 0.003525
2016-08-01 20:53:24,885:INFO:nodes:No pickle file found for accessor interface/VMware Network Adapter VMnet8/bytes_sent
2016-08-01 20:53:24,887:ERROR:app:Exception on /api/interface/VMware Network Adapter VMnet8/bytes_sent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, values_file)
TypeError: write() argument must be str, not bytes
2016-08-01 20:53:24,915:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /api/interface/VMware%20Network%20Adapter%20VMnet8/bytes_sent?delta=1&units=K HTTP/1.1" 500 3356 0.033795
2016-08-01 20:53:24,918:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /static/js/smoothie.js?_=1470102804706 HTTP/1.1" 200 33107 0.002002
2016-08-01 20:53:24,926:INFO:nodes:No pickle file found for accessor interface/VMware Network Adapter VMnet8/bytes_recv
2016-08-01 20:53:24,926:ERROR:app:Exception on /api/interface/VMware Network Adapter VMnet8/bytes_recv [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, values_file)
TypeError: write() argument must be str, not bytes
2016-08-01 20:53:24,948:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /api/interface/VMware%20Network%20Adapter%20VMnet8/bytes_recv?delta=1&units=K HTTP/1.1" 500 3356 0.027585
2016-08-01 20:53:24,951:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /static/js/smoothie.js?_=1470102804707 HTTP/1.1" 200 33107 0.002003
2016-08-01 20:53:24,959:INFO:nodes:No pickle file found for accessor interface/Ethernet/bytes_sent
2016-08-01 20:53:24,959:ERROR:app:Exception on /api/interface/Ethernet/bytes_sent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, values_file)
TypeError: write() argument must be str, not bytes
2016-08-01 20:53:24,983:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /api/interface/Ethernet/bytes_sent?delta=1&units=K HTTP/1.1" 500 3356 0.028150
2016-08-01 20:53:24,985:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:24] "GET /static/js/smoothie.js?_=1470102804708 HTTP/1.1" 200 33107 0.001267
2016-08-01 20:53:24,993:INFO:nodes:No pickle file found for accessor interface/Ethernet/bytes_recv
2016-08-01 20:53:24,993:ERROR:app:Exception on /api/interface/Ethernet/bytes_recv [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, values_file)
TypeError: write() argument must be str, not bytes
2016-08-01 20:53:25,016:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:25] "GET /api/interface/Ethernet/bytes_recv?delta=1&units=K HTTP/1.1" 500 3356 0.027515
2016-08-01 20:53:25,019:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:25] "GET /static/js/smoothie.js?_=1470102804709 HTTP/1.1" 200 33107 0.002002
2016-08-01 20:53:25,027:INFO:nodes:No pickle file found for accessor interface/Ethernet 3/bytes_sent
2016-08-01 20:53:25,027:ERROR:app:Exception on /api/interface/Ethernet 3/bytes_sent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, values_file)
TypeError: write() argument must be str, not bytes
2016-08-01 20:53:25,050:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:25] "GET /api/interface/Ethernet%203/bytes_sent?delta=1&units=K HTTP/1.1" 500 3356 0.027025
2016-08-01 20:53:25,066:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:25] "GET /static/js/smoothie.js?_=1470102804710 HTTP/1.1" 200 33107 0.000983
2016-08-01 20:53:25,080:INFO:nodes:No pickle file found for accessor interface/Ethernet 3/bytes_recv
2016-08-01 20:53:25,080:ERROR:app:Exception on /api/interface/Ethernet 3/bytes_recv [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, values_file)
TypeError: write() argument must be str, not bytes
2016-08-01 20:53:25,103:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:25] "GET /api/interface/Ethernet%203/bytes_recv?delta=1&units=K HTTP/1.1" 500 3356 0.027054
2016-08-01 20:53:25,106:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:25] "GET /static/js/smoothie.js?_=1470102804711 HTTP/1.1" 200 33107 0.002002
2016-08-01 20:53:25,114:INFO:nodes:No pickle file found for accessor interface/Loopback Pseudo-Interface 1/bytes_sent
2016-08-01 20:53:25,115:ERROR:app:Exception on /api/interface/Loopback Pseudo-Interface 1/bytes_sent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, values_file)
TypeError: write() argument must be str, not bytes
2016-08-01 20:53:25,138:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:25] "GET /api/interface/Loopback%20Pseudo-Interface%201/bytes_sent?delta=1&units=K HTTP/1.1" 500 3356 0.028025
2016-08-01 20:53:25,154:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:25] "GET /static/js/smoothie.js?_=1470102804712 HTTP/1.1" 200 33107 0.002003
2016-08-01 20:53:25,162:INFO:nodes:No pickle file found for accessor interface/Loopback Pseudo-Interface 1/bytes_recv
2016-08-01 20:53:25,163:ERROR:app:Exception on /api/interface/Loopback Pseudo-Interface 1/bytes_recv [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, values_file)
TypeError: write() argument must be str, not bytes
2016-08-01 20:53:25,186:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:25] "GET /api/interface/Loopback%20Pseudo-Interface%201/bytes_recv?delta=1&units=K HTTP/1.1" 500 3356 0.028044
2016-08-01 20:53:25,209:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:25] "GET /static/js/smoothie.js?_=1470102804713 HTTP/1.1" 200 33107 0.002002
2016-08-01 20:53:25,218:INFO:nodes:No pickle file found for accessor interface/VMware Network Adapter VMnet1/bytes_sent
2016-08-01 20:53:25,218:ERROR:app:Exception on /api/interface/VMware Network Adapter VMnet1/bytes_sent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, values_file)
TypeError: write() argument must be str, not bytes
2016-08-01 20:53:25,241:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:25] "GET /api/interface/VMware%20Network%20Adapter%20VMnet1/bytes_sent?delta=1&units=K HTTP/1.1" 500 3356 0.028010
2016-08-01 20:53:25,250:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:25] "GET /static/js/smoothie.js?_=1470102804714 HTTP/1.1" 200 33107 0.001001
2016-08-01 20:53:25,259:INFO:nodes:No pickle file found for accessor interface/VMware Network Adapter VMnet1/bytes_recv
2016-08-01 20:53:25,259:ERROR:app:Exception on /api/interface/VMware Network Adapter VMnet1/bytes_recv [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, values_file)
TypeError: write() argument must be str, not bytes
2016-08-01 20:53:25,284:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:25] "GET /api/interface/VMware%20Network%20Adapter%20VMnet1/bytes_recv?delta=1&units=K HTTP/1.1" 500 3356 0.029790
2016-08-01 20:53:25,811:INFO:handler:127.0.0.1 - - [2016-08-01 20:53:25] "GET /api/cpu/percent HTTP/1.1" 200 330 1.002352
2016-08-01 20:54:11,870:INFO:ncpa_windows:Parsed config from: ['C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg', 'C:\\Users\\Jake\\Documents\\ncpa\\agent\\etc\\ncpa.cfg.d\\example.cfg']
2016-08-01 20:54:11,870:INFO:ncpa_windows:Looking for plugins at: C:\Users\Jake\Documents\ncpa\agent\plugins
2016-08-01 20:54:11,870:INFO:ncpa_windows:Using SSL version TLSv1_2
2016-08-01 20:54:17,606:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:17] "GET /gui/stats HTTP/1.1" 302 517 0.001983
2016-08-01 20:54:17,619:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:17] "GET /login HTTP/1.1" 200 2954 0.010994
2016-08-01 20:54:17,906:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:17] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 188 0.206063
2016-08-01 20:54:17,915:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:17] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 189 0.001997
2016-08-01 20:54:17,917:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:17] "GET /static/css/ncpa.css HTTP/1.1" 304 187 0.001000
2016-08-01 20:54:17,919:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:17] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 189 0.001001
2016-08-01 20:54:17,921:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:17] "GET /static/js/d3.v4.min.js HTTP/1.1" 304 189 0.001019
2016-08-01 20:54:17,922:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:17] "GET /static/js/jquery.2.2.4.min.js HTTP/1.1" 304 188 0.000999
2016-08-01 20:54:18,032:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:18] "GET /static/img/ncpa.png HTTP/1.1" 200 18888 0.001001
2016-08-01 20:54:18,037:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:18] "GET /static/img/ncpa.png HTTP/1.1" 200 18888 0.001000
2016-08-01 20:54:18,595:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:18] "POST /login HTTP/1.1" 200 3100 0.002002
2016-08-01 20:54:19,394:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "POST /login HTTP/1.1" 302 572 0.001002
2016-08-01 20:54:19,402:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /gui/stats HTTP/1.1" 200 6173 0.004996
2016-08-01 20:54:19,506:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /graph/cpu/percent HTTP/1.1" 200 5556 0.010010
2016-08-01 20:54:19,510:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /graph/memory/virtual/percent HTTP/1.1" 200 5611 0.004004
2016-08-01 20:54:19,514:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /api/disk/logical HTTP/1.1" 200 453 0.003003
2016-08-01 20:54:19,569:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /api/interface/ HTTP/1.1" 200 1501 0.055053
2016-08-01 20:54:19,571:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /static/js/smoothie.js?_=1470102859443 HTTP/1.1" 200 33107 0.001001
2016-08-01 20:54:19,584:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /static/js/smoothie.js?_=1470102859444 HTTP/1.1" 200 33107 0.001502
2016-08-01 20:54:19,591:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /api/memory/virtual/percent HTTP/1.1" 200 269 0.003138
2016-08-01 20:54:19,597:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /graph/disk/logical/C:%7C/used_percent HTTP/1.1" 200 5646 0.003003
2016-08-01 20:54:19,602:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /graph/interface/Ethernet%203/bytes_sent?delta=1&units=K HTTP/1.1" 200 5677 0.004004
2016-08-01 20:54:19,606:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /graph/interface/Ethernet%203/bytes_recv?delta=1&units=K HTTP/1.1" 200 5677 0.003003
2016-08-01 20:54:19,609:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /static/js/smoothie.js?_=1470102859445 HTTP/1.1" 200 33107 0.001979
2016-08-01 20:54:19,612:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /graph/interface/Ethernet/bytes_sent?delta=1&units=K HTTP/1.1" 200 5680 0.003003
2016-08-01 20:54:19,616:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /graph/interface/Ethernet/bytes_recv?delta=1&units=K HTTP/1.1" 200 5654 0.003003
2016-08-01 20:54:19,618:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /static/js/smoothie.js?_=1470102859446 HTTP/1.1" 200 33107 0.001000
2016-08-01 20:54:19,623:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /graph/interface/VMware%20Network%20Adapter%20VMnet8/bytes_sent?delta=1&units=K HTTP/1.1" 200 5759 0.004006
2016-08-01 20:54:19,625:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /static/js/smoothie.js?_=1470102859447 HTTP/1.1" 200 33107 0.001000
2016-08-01 20:54:19,629:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /graph/interface/VMware%20Network%20Adapter%20VMnet8/bytes_recv?delta=1&units=K HTTP/1.1" 200 5759 0.003003
2016-08-01 20:54:19,634:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /graph/interface/Loopback%20Pseudo-Interface%201/bytes_sent?delta=1&units=K HTTP/1.1" 200 5775 0.004004
2016-08-01 20:54:19,636:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /static/js/smoothie.js?_=1470102859448 HTTP/1.1" 200 33107 0.001000
2016-08-01 20:54:19,640:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /graph/interface/Loopback%20Pseudo-Interface%201/bytes_recv?delta=1&units=K HTTP/1.1" 200 5749 0.003003
2016-08-01 20:54:19,642:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /static/js/smoothie.js?_=1470102859449 HTTP/1.1" 200 33107 0.000985
2016-08-01 20:54:19,646:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /graph/interface/VMware%20Network%20Adapter%20VMnet1/bytes_sent?delta=1&units=K HTTP/1.1" 200 5759 0.003003
2016-08-01 20:54:19,648:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /static/js/smoothie.js?_=1470102859450 HTTP/1.1" 200 33107 0.001001
2016-08-01 20:54:19,652:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /graph/interface/VMware%20Network%20Adapter%20VMnet1/bytes_recv?delta=1&units=K HTTP/1.1" 200 5772 0.003004
2016-08-01 20:54:19,656:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /api/disk/logical/C:%7C/used_percent HTTP/1.1" 200 274 0.003002
2016-08-01 20:54:19,658:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /static/js/smoothie.js?_=1470102859451 HTTP/1.1" 200 33107 0.001000
2016-08-01 20:54:19,664:INFO:nodes:No pickle file found for accessor interface/Ethernet 3/bytes_sent
2016-08-01 20:54:19,665:ERROR:app:Exception on /api/interface/Ethernet 3/bytes_sent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, str(values_file))
TypeError: file must have a 'write' attribute
2016-08-01 20:54:19,692:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /api/interface/Ethernet%203/bytes_sent?delta=1&units=K HTTP/1.1" 500 3356 0.034206
2016-08-01 20:54:19,694:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /static/js/smoothie.js?_=1470102859452 HTTP/1.1" 200 33107 0.001015
2016-08-01 20:54:19,699:INFO:nodes:No pickle file found for accessor interface/Ethernet 3/bytes_recv
2016-08-01 20:54:19,699:ERROR:app:Exception on /api/interface/Ethernet 3/bytes_recv [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, str(values_file))
TypeError: file must have a 'write' attribute
2016-08-01 20:54:19,730:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /api/interface/Ethernet%203/bytes_recv?delta=1&units=K HTTP/1.1" 500 3356 0.036019
2016-08-01 20:54:19,732:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /static/js/smoothie.js?_=1470102859453 HTTP/1.1" 200 33107 0.001019
2016-08-01 20:54:19,737:INFO:nodes:No pickle file found for accessor interface/Ethernet/bytes_sent
2016-08-01 20:54:19,738:ERROR:app:Exception on /api/interface/Ethernet/bytes_sent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, str(values_file))
TypeError: file must have a 'write' attribute
2016-08-01 20:54:19,761:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /api/interface/Ethernet/bytes_sent?delta=1&units=K HTTP/1.1" 500 3356 0.028028
2016-08-01 20:54:19,763:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /static/js/smoothie.js?_=1470102859454 HTTP/1.1" 200 33107 0.001021
2016-08-01 20:54:19,768:INFO:nodes:No pickle file found for accessor interface/Ethernet/bytes_recv
2016-08-01 20:54:19,768:ERROR:app:Exception on /api/interface/Ethernet/bytes_recv [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, str(values_file))
TypeError: file must have a 'write' attribute
2016-08-01 20:54:19,791:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /api/interface/Ethernet/bytes_recv?delta=1&units=K HTTP/1.1" 500 3356 0.026544
2016-08-01 20:54:19,793:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /static/js/smoothie.js?_=1470102859455 HTTP/1.1" 200 33107 0.001016
2016-08-01 20:54:19,798:INFO:nodes:No pickle file found for accessor interface/VMware Network Adapter VMnet8/bytes_sent
2016-08-01 20:54:19,798:ERROR:app:Exception on /api/interface/VMware Network Adapter VMnet8/bytes_sent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, str(values_file))
TypeError: file must have a 'write' attribute
2016-08-01 20:54:19,822:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /api/interface/VMware%20Network%20Adapter%20VMnet8/bytes_sent?delta=1&units=K HTTP/1.1" 500 3356 0.028028
2016-08-01 20:54:19,850:INFO:nodes:No pickle file found for accessor interface/VMware Network Adapter VMnet8/bytes_recv
2016-08-01 20:54:19,851:ERROR:app:Exception on /api/interface/VMware Network Adapter VMnet8/bytes_recv [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, str(values_file))
TypeError: file must have a 'write' attribute
2016-08-01 20:54:19,875:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /api/interface/VMware%20Network%20Adapter%20VMnet8/bytes_recv?delta=1&units=K HTTP/1.1" 500 3356 0.028525
2016-08-01 20:54:19,881:INFO:nodes:No pickle file found for accessor interface/VMware Network Adapter VMnet1/bytes_sent
2016-08-01 20:54:19,881:ERROR:app:Exception on /api/interface/VMware Network Adapter VMnet1/bytes_sent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, str(values_file))
TypeError: file must have a 'write' attribute
2016-08-01 20:54:19,906:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /api/interface/VMware%20Network%20Adapter%20VMnet1/bytes_sent?delta=1&units=K HTTP/1.1" 500 3356 0.029225
2016-08-01 20:54:19,934:INFO:nodes:No pickle file found for accessor interface/Loopback Pseudo-Interface 1/bytes_sent
2016-08-01 20:54:19,934:ERROR:app:Exception on /api/interface/Loopback Pseudo-Interface 1/bytes_sent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, str(values_file))
TypeError: file must have a 'write' attribute
2016-08-01 20:54:19,960:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:19] "GET /api/interface/Loopback%20Pseudo-Interface%201/bytes_sent?delta=1&units=K HTTP/1.1" 500 3356 0.030014
2016-08-01 20:54:20,013:INFO:nodes:No pickle file found for accessor interface/VMware Network Adapter VMnet1/bytes_recv
2016-08-01 20:54:20,014:ERROR:app:Exception on /api/interface/VMware Network Adapter VMnet1/bytes_recv [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, str(values_file))
TypeError: file must have a 'write' attribute
2016-08-01 20:54:20,038:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:20] "GET /api/interface/VMware%20Network%20Adapter%20VMnet1/bytes_recv?delta=1&units=K HTTP/1.1" 500 3356 0.029029
2016-08-01 20:54:20,067:INFO:nodes:No pickle file found for accessor interface/Loopback Pseudo-Interface 1/bytes_recv
2016-08-01 20:54:20,068:ERROR:app:Exception on /api/interface/Loopback Pseudo-Interface 1/bytes_recv [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 554, in api
    value = node.walk(**sane_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 129, in walk
    values = self.get_delta_values(values, kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 155, in get_delta_values
    values = self.deltaize_values(values, accessor)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\nodes.py", line 363, in deltaize_values
    pickle.dump(values, str(values_file))
TypeError: file must have a 'write' attribute
2016-08-01 20:54:20,093:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:20] "GET /api/interface/Loopback%20Pseudo-Interface%201/bytes_recv?delta=1&units=K HTTP/1.1" 500 3356 0.029520
2016-08-01 20:54:20,583:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:20] "GET /api/cpu/percent HTTP/1.1" 200 331 1.003567
2016-08-01 20:54:54,827:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:54] "GET /gui/top HTTP/1.1" 200 3374 0.004003
2016-08-01 20:54:54,831:ERROR:app:Exception on /api-websocket/disk/logical/C:|/used_percent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 331, in send_frame
    self.raw_write(header + message)
TypeError: can't concat bytes to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 236, in api_websocket
    message = ws.receive()
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 304, in receive
    return self.read_message()
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 273, in read_message
    self.handle_close(header, payload)
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 182, in handle_close
    self.close(code, payload)
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 366, in close
    self.send_frame(message, opcode=self.OPCODE_CLOSE)
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 335, in send_frame
    import ipdb; ipdb.set_trace()
ImportError: No module named 'ipdb'
2016-08-01 20:54:54,870:ERROR:app:Exception on /api-websocket/memory/virtual/percent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 331, in send_frame
    self.raw_write(header + message)
TypeError: can't concat bytes to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 236, in api_websocket
    message = ws.receive()
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 304, in receive
    return self.read_message()
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 273, in read_message
    self.handle_close(header, payload)
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 182, in handle_close
    self.close(code, payload)
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 366, in close
    self.send_frame(message, opcode=self.OPCODE_CLOSE)
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 335, in send_frame
    import ipdb; ipdb.set_trace()
ImportError: No module named 'ipdb'
2016-08-01 20:54:55,015:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:55] "GET /top HTTP/1.1" 200 7913 0.007037
2016-08-01 20:54:55,048:INFO:handler:127.0.0.1 - - [2016-08-01 20:54:55] "GET /static/js/smoothie.js?_=1470102894931 HTTP/1.1" 200 33107 0.001001
2016-08-01 20:54:55,232:ERROR:app:Exception on /api-websocket/cpu/percent [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 331, in send_frame
    self.raw_write(header + message)
TypeError: can't concat bytes to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 236, in api_websocket
    message = ws.receive()
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 304, in receive
    return self.read_message()
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 273, in read_message
    self.handle_close(header, payload)
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 182, in handle_close
    self.close(code, payload)
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 366, in close
    self.send_frame(message, opcode=self.OPCODE_CLOSE)
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 335, in send_frame
    import ipdb; ipdb.set_trace()
ImportError: No module named 'ipdb'
2016-08-01 20:54:56,086:ERROR:app:Exception on /top-websocket/ [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 326, in top_websocket
    ws.send(json_val)
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 348, in send
    self.send_frame(message, opcode)
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 328, in send_frame
    header = Header.encode_header(True, opcode, b'', len(message), 0)
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 568, in encode_header
    return bytes(bytearray(header))
TypeError: an integer is required
2016-08-01 20:55:38,137:INFO:handler:127.0.0.1 - - [2016-08-01 20:55:38] "GET /gui/top HTTP/1.1" 200 3374 0.003003
2016-08-01 20:55:38,323:INFO:handler:127.0.0.1 - - [2016-08-01 20:55:38] "GET /top HTTP/1.1" 200 7913 0.001986
2016-08-01 20:55:38,353:INFO:handler:127.0.0.1 - - [2016-08-01 20:55:38] "GET /static/js/smoothie.js?_=1470102938281 HTTP/1.1" 200 33107 0.002002
2016-08-01 20:55:39,268:ERROR:app:Exception on /top-websocket/ [GET]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 75, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Jake\Documents\ncpa\agent\listener\server.py", line 326, in top_websocket
    ws.send(json_val)
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 348, in send
    self.send_frame(message, opcode)
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 328, in send_frame
    header = Header.encode_header(True, opcode, b'', len(message), 0)
  File "C:\Python35\lib\site-packages\gevent_websocket-0.9.5-py3.5.egg\geventwebsocket\websocket.py", line 568, in encode_header
    return bytes(bytearray(header))
TypeError: an integer is required
